album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('', views.AlbumTemplateView.as_view(), name="albums"),
    path('lists/', views.AlbumList.as_view(), name="albums_list"),
    path('<slug:album>/photos', views.PhotoTemplateView.as_view(), name="photos_list"),
    path('<slug:album>/photos/list/', views.PhotoList.as_view(), name="photos")
]

arachnid/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('staff/', include('staff.urls', namespace="staff")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('albums/', include('album.urls', namespace='album'))
    #path('albums/', include('album.urls', namespace="album"))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    path('admissions',
        views.AdmissionView.as_view(),
        name="admissions"),

    path('news',
        views.NewsView.as_view(),
        name="news"),

    path('news/details/<int:pk>', views.NewsDetailView.as_view(),
        name="news_detail"),

    path('organizations',views.OrganizationListView.as_view(),name="organizations"),
    path('organizations/details/<int:pk>', views.OrganizationDetailView.as_view(), name="organization_details"),


    path('life_science', views.LifeListView.as_view(), name="life_science"),
    path('life_science/details/<int:pk>', views.LifeDetailView.as_view(),name="life_science_detail"),

    path('applied_science', views.AppliedListView.as_view(),name="applied_science"),
    path('applied_science/details/<int:pk>', views.AppliedDetailView.as_view(),name="applied_science_detail"),


    path('about',
        views.AboutView.as_view(),
        name="about"
    ),

    path('faqs',
        views.FAQsView.as_view(),
        name="faqs"
    )
]

staff/urls.py
from django.urls import path, include
from . import views
from album import views as album_views
from django.contrib.auth import views as auth_view

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcements'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name="create_announcement"),
    path('announcements/view/<int:pk>/', views.view_file, name="view_file"),

    path('news/', views.NewsListView.as_view(), name="news"),
    path('news/create/', views.NewsCreateView.as_view(), name="create_news"),
    path('news/update/<int:pk>/', views.NewsUpdateView.as_view(), name="update_news"),
    path('news/delete/<int:pk>/', views.NewsDeleteView.as_view(), name="delete_news"),
    path('news/publish/<int:pk>/', views.publish_news, name="publish"),

    path('organizations/', views.OrganizationListView.as_view(), name="organizations"),
    path('organizations/create/', views.OrganizationCreateView.as_view(), name="create_organization"),
    path('organizations/delete/<int:pk>/', views.OrganizationDeleteView.as_view(), name="delete_organization"),
    path('organizations/update/<int:pk>/', views.OrganizationUpdateView.as_view(), name="update_organization"),
    path('organization/details/<int:pk>/', views.OrganizationDetailView.as_view(), name="organization_detail"),

    path('research/', views.ResearchListView.as_view(), name="research"),
    path('research/create/', views.ResearchCreateView.as_view(), name="create_research"),
    path('research/delete/<int:pk>/', views.ResearchDeleteView.as_view(), name="delete_research"),
    path("research/update/<int:pk>/", views.ResearchUpdateView.as_view(), name="update_research"),
    path("research/details/<int:pk>/", views.ResearchDetailView.as_view(), name="research_detail"),
    path('research/details/<int:pk>/add_proponent/', views.add_proponent_to_research, name="add_proponent_to_research"),

    path('accounts/login/', auth_view.login, name="login"),
    path('accounts/logout/', auth_view.logout, name="logout", kwargs={'next_page': '/'}),

    # For the organization hr
    path('organizations/<organization>/hr/', views.OrganizationHRListView.as_view(), name="organization_hr_list"),
    path('organizations/<organization>/hr/create', views.OrganizationHRCreateView.as_view(), name="organization_hr_create"),
    path('organizations/<organization>/hr/delete/<int:pk>/', views.OrganizationHRDeleteView.as_view(), name="organization_hr_delete"),
    path('organizations/<organization>/hr/update/<int:pk>/', views.OrganizationHRUpdateView.as_view(), name="organization_hr_update"),
    path('organizations/<organization>/hr/details/<int:pk>/', views.OrganizationHRDetailView.as_view(), name="organization_hr_detail"),

    # for the albums section
    path('albums/', album_views.AlbumListView.as_view(), name="albums"),
    path('albums/create', album_views.AlbumCreateView.as_view(), name="create_album"),
    path('albums/delete/<int:pk>/', album_views.AlbumDeleteView.as_view(), name="album_delete"),
    path('albums/<slug:album>/photos/delete/<int:pk>/', album_views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('albums/<slug:album>/photos', album_views.PhotosListView.as_view(), name="photos"),
    path('albums/<slug:album>/photos/upload', album_views.PhotoUploadView.as_view(), name="upload_photo")

]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import Http404
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView
from staff.models import Announcement, News, Organization, ResearchPaper
from django.utils import timezone
# Create your views here.


# Returns a list of announcements and news
# Does not check if the query result is none
def index(request):
    announcements = list(Announcement.objects.order_by('-date_created')[:5])
    news = list(News.objects.order_by('-published_date')[:5])
    #announcements = get_list_or_404(Announcement.objects.order_by('-date_created')[:5])
    #news = get_list_or_404(News.objects.order_by('-published_date')[:5])
    return render(request, 'main/index.html', {'announcements': announcements, 'news': news})


class AnnouncementDetailView(DetailView):
    model = Announcement
    context_object_name = "announcement"
    pk_url_kwarg = 'pk'

class AdmissionView(TemplateView):
    template_name = 'main/admissions.html'

class NewsView(ListView):
    template_name = 'main/news.html'
    model = News
    context_object_name = "news"
    def get_queryset(self):
        return News.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class NewsDetailView(DetailView):
    template_name = "main/news_details.html"
    model = News
    context_object_name = "news"
    pk_url_kwarg = 'pk'

class OrganizationListView(ListView):
    template_name = 'main/orgs.html'
    model = Organization
    context_object_name = "organizations"
    def get_queryset(self):
        return Organization.objects.all()

class OrganizationDetailView(DetailView):
    template_name = 'main/orgs_detail.html'
    model = Organization
    context_object_name = "organization"
    pk_url_kwarg = "pk"
    



class AppliedListView(ListView):
    template_name = 'main/appliedScience.html'
    model = ResearchPaper
    context_object_name = "research_paper"
    def get_queryset(self):
        return ResearchPaper.objects.filter(category="Applied").order_by('-published_date')

class AppliedDetailView(DetailView):
    template_name = 'main/appliedScience_detail.html'
    model = ResearchPaper
    context_object_name = "applied_science_research"
    pk_url_kwarg = "pk"

class LifeListView(ListView):
    template_name = 'main/lifeScience.html'
    model = ResearchPaper
    context_object_name = "research_paper"
    def get_queryset(self):
        return ResearchPaper.objects.filter(category="Life").order_by('-published_date')

class LifeDetailView(DetailView):
    template_name = 'main/lifeScience_detail.html'
    model = ResearchPaper
    context_object_name = "life_science_research"
    pk_url_kwarg = "pk"

class AboutView(TemplateView):
    template_name = 'main/about.html'

class FAQsView(TemplateView):
    template_name = 'main/faqs.html'


#############################
# THIS IS FOR THE STAFF APP #
#############################

templates/main/appliedScience_detail.html
{% extends 'base_2.html'%}
{% block title %}
  Applied Science
{% endblock %}
{% block main_content %}
  <div class="ui container segment">
    <a href="{% url 'main:applied_science' %}" class="ui basic icon labeled button"><i class="ui angle double left icon"></i>All Papers</a>
    <div class="ui stackable celled grid">
      <div class="center aligned row">
        <div class="column">
          <h1 class="ui header">
            {{ object.title }}
          </h1>
        </div>
      </div>
      <div class="row">
        <div class="ten wide computer left floated sixteen wide tablet column">
          <div class="ui raised segment">
            <h2 class="ui header">Abstract</h2>
            <div class="ui divider"></div>
            {{ object.abstract }}
          </div>
        </div>
        <div class="six wide computer rigt floated sixteen wide tablet column">
          <div class="ui raised segment">
            <h2 class="ui header">Proponent{{ objects.proponents.all|pluralize}}</h2>
            <ul class="ui list">
              {% for proponent in object.proponents.all %}
              <li class="ui item">{{ proponent.first_name|slice:"1"}}. {{ proponent.middle_name|slice:"1" }}. {{proponent.last_name }}</li>
              {% endfor %}
            </ul>
            <h2 class="ui header">Published: </h2>
            <p class="ui description">{{ object.published_date|date:"M d, Y"}}</p>
            <div class="ui labeled button">
              <a href="{{ object.file.url }}" class="ui green icon button">Download</a>
              <div class="ui basic green left pointing label">
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/main/footer.html
{% load staticfiles %}

<div class="ui vertical footer segment">
	<div class="ui container">
		<div class="ui stackable inverted divided equal height stackable grid">
			<div class="three wide column">
					<h3 class="ui inverted header">SECTIONS</h3>
					<div class="ui inverted link list">
						<a class="item upper-bound-list" href="{% url 'main:index' %}">Home</a>
						<a class="item upper-bound-list" href="{% url 'main:admissions' %}">Admissions</a>
						<a class="item upper-bound-list" href="{% url 'main:news' %}">News</a>
						<div class="item upper-bound-list">
							Archives
							<div class="ui list">
								<a class="item lower-bound-list" href="documents.html">Documents</a>
								<a class="item lower-bound-list" href="{% url 'album:albums' %}">Album</a>
							</div>
						</div>
						<a class="item upper-bound-list" href="{% url 'main:organizations' %}">Organizations</a>
						<div class="item upper-bound-list">
							Research
							<div class="ui list">
								<a class="item lower-bound-list" href="{% url 'main:applied_science' %}">Applied Science</a>
								<a class="item lower-bound-list" href="{% url 'main:life_science' %}">Life Science</a>
							</div>
						</div>
						<a class="item upper-bound-list" href="{% url 'main:about' %}">About</a>
						<a class="item upper-bound-list" href="{% url 'main:faqs' %}">FAQs</a>
					</div>
			</div>
			<div class="four wide column">
				<h3 class="ui inverted header">REACH US ON</h3>
				<div class="ui inverted link list">
					<div class="row" id="footerReach">
					<a href="#" class="item"><img src="{% static 'img/facebook.png' %}"></a>
					<a href="#" class="item"><img src="{% static 'img/twitter.png' %}"></a>
					<a href="#" class="item"><img src="{% static 'img/youtube.png' %}"></a>
					<a href="#" class="item"><img src="{% static 'img/instagram.png' %}"></a>
					</div>
				</div>
				<div class="ui divider"></div>
				<h3 class="ui inverted header">CONTACT US</h3>
				<div class="column description"><i class="call icon"></i> 0929 xxx xxxx</div>
				<div class="column description"><i class="mail icon"></i> quescimail@gmail.com</div>
		</div>
				<div class="seven wide column">
						<br>
						<div class="text container" id="footerQsci">Quezon Science High School</div>
						<div class="description aligned center"><i class="marker icon"></i> Brgay. Isabang, Tayabas City, Quezon Province</div>
						<div class="ui divider"></div>
						<p id="footerRights">All Rights Reserved 2017</p>
				</div>
		</div>
		</div>
	</div>

templates/main/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
  Home - QSHS
{% endblock %}
{% block style %}
  .ui.text.container {
    margin-top: 0em;
  }
  .ui.text.container h1 {
    font-weight: bold;
    font-size: 3em;
    text-shadow: 2px 2px 4px black;
  }
  #header_segment .ui.header {
    float: left;
  }

{% endblock %}
{% block linkstyle %}
<link rel="stylesheet" href="{% static 'css/glider.css' %}">
{% endblock %}
{% block main_content %}
    <div class="dimmed pusher">
        <div class="ui masthead center aligned segment">

            <div class="ui green secondary large menu"  id="home-navbar">
                <a class="item" href="{% url 'main:index' %}">
                  <div class="ui header">
                    <img class="logo" src="{% static 'img/logo.png' %}">
                    QSHS
                  </div>
                </a>
                <div class="ui right item">
                    <a class="active item" href="{% url 'main:index' %}">Home</a>
                <a class="item" href="{% url 'main:admissions' %}">Admissions</a>
                <a class="item" href="{% url 'main:news' %}">News</a>
                <div class="ui dropdown {% block archives %} {% endblock %}item">
                  Archives
                  <i class="ui dropdown icon"></i>
                  <div class="menu">
                    <a class="{% block archive_documents %} {% endblock %}item" href="#">Documents</a>
                    <div class="ui divider"></div>
                    <a class="{% block album %} {% endblock %}item" href="{% url 'album:albums' %}">Album</a>
                  </div>
                </div>
                <a class="item" href="{% url 'main:organizations' %}">Organizations</a>
                <div class="ui dropdown item">
    							Research
    							<i class="ui dropdown icon"></i>
    							<div class="menu">
    								<a class="item" href="{% url 'main:applied_science' %}">Applied Science</a>
    								<div class="ui divider"></div>
    								<a class="item" href="{% url 'main:life_science' %}">Life Science</a>
    							</div>
    						</div>
                <a class="item" href="{% url 'main:about' %}">About</a>
                <a class="item" href="{% url 'main:faqs' %}">FAQs</a>
                <div class="right menu">
                  <div class="item">
                    {% if user.is_authenticated %}
                    <a class="ui inverted green button" href="{% url 'staff:index' %}">
                        <i class="universal access icon"></i>
                        Faculty/Staff
                    </a>
                    {% else %}
                    <a class="ui inverted green button" href="{% url 'staff:login' %}">
                        <i class="sign in icon"></i>
                        Faculty/Staff
                    </a>
                    {% endif %}
                  </div>
                </div>
                </div>
            </div>
            <div class="ui text container" id="banner-text">
              <h1 class="ui header">Quezon Science High School</h1>
              <div class="ui horizontal section divider">
                  <h3>Honorem | Excellencia | Servitium</h3>
              </div>
            </div>
          </div>
            <div class="glider-contain multiple" style="margin-top: 0em;" id="img-slides">
              <button type="button" name="button" class="glider-prev">
                <i class="ui left angle icon"></i>
              </button>
              <div class="glider" style="height: 400px">
                  <div class="ui small image">
                    <img src="{% static 'img/qshs/Dorm 2.jpg' %}" alt="">
                  </div>
                  <div class="ui small image">
                    <img src="{% static 'img/7.jpg' %}" alt="">
                  </div>
                  <div class="ui small image">
                    <img src="{% static 'img/5.jpeg' %}" alt="">
                  </div>
              </div>
              <button type="button" name="button" class="glider-next">
                <i class="ui right angle icon"></i>
              </button>
              <div id="dots" class="glider-dots">

              </div>
            </div>




        <!-- ANNOUNCEMENTS -->

        <div class="ui feature vertical stripe segments">
              <div class="ui middle aligned stackable internally celled grid container" id="header_segment">
                <div class="row">
                  <div class="center aligned column">
                    <h1 class="ui header">
                      Bulletin Board
                    </h1>
                  </div>
                </div>
                <div class="ui row segment">
                  <div class="eight wide column">
                    <h3 class="ui center aligned header">Latest News</h3>
                  </div>
                  <div class="ui middle aligned padded internally celled grid stackable container">
                    <div class="row">
                      <div class="ui eight wide computer sixteen wide tablet column">
                        {% if news %}
                          <div class="ui fluid card">
                            <a class="image" href="{% url 'main:news_detail' pk=news.0.pk %}">
                              <img src="{{ news.0.headline_image.url }}" alt="">
                            </a>
                            <div class="content">
                              <a href="{% url 'main:news_detail' pk=news.0.pk %}" class="header">
                                {{ news.0.headline|safe }}
                              </a>
                              <div class="meta">
                                <span>{{ news.0.published_date|date:"M d, Y" }}</span>
                              </div>
                              <div class="description">
                                {{ news.0.lead_text|safe }}
                              </div>
                            </div>
                          </div>
                        {% endif %}
                      </div>
                      <div class="ui six wide computer sixteen wide tablet right floated column">
                        <div class="ui relaxed items">
                          {% if news %}
                            {% for news in news %}
                              <div class="item">
                                <a class="ui small image" href="{% url 'main:news_detail' pk=news.pk %}">
                                  <img src="{{ news.headline_image.url }}" alt="">
                                </a>
                                <div class="content">
                                  <a href="{% url 'main:news_detail' pk=news.pk %}" class="header">{{ news.headline|safe }}</a>
                                  <div class="meta">
                                    {{ news.published_date|date:"M d, Y"}}
                                  </div>
                                  <div class="description">
                                    {{ news.lead_text|truncatechars:100 }}
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                          {% else %}
                            <div class="item">
                              No news yet
                            </div>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="ui row segment">
                  <div class="eight wide column">
                    <h3 class="ui center aligned header">Announcements</h3>
                  </div>
                  <div class="ui middle aligned padded internally celled grid stackable container">
                    <div class="row">
                      <div class="ui eight wide computer sixteen wide tablet column">
                        {% if announcements %}
                          <div class="ui fluid card">
                            <a class="image" href="#">
                              <img src="{% static 'img/stock/macaw-poly.jpg' %}" alt="">
                            </a>
                            <div class="content">
                              <a href="{% url 'main:news_detail' pk=announcements.0.pk %}" class="header">
                                {{ announcements.0.title|safe }}
                              </a>
                              <div class="meta">
                                <span>{{ announcements.0.date_created|date:"M d, Y" }}</span>
                              </div>
                              <div class="description">
                                {{ announcements.0.description }}
                              </div>
                            </div>
                          </div>
                        {% endif %}
                      </div>
                      <div class="ui six wide computer sixteen wide tablet right floated column">
                        <div class="ui relaxed items">
                          {% if announcements %}
                            {% for announcement in announcements %}
                              <div class="item">
                                <a class="ui small image" href="#">
                                  <img src="{% static 'img/stock/macaw-poly.jpg' %}" alt="">
                                </a>
                                <div class="content">
                                  <a href="{% url 'staff:view_file' pk=announcement.pk %}" class="header">
                                      {{ announcement.title }}
                                  </a>
                                  <div class="meta">
                                    Published {{ announcement.date_created|date:"M d, Y"}}
                                  </div>
                                  <div class="description">
                                    {{ announcement.description }}
                                  </div>
                                </div>
                              </div>
                            {% endfor %}
                          {% else %}
                            <div class="item">
                              No news yet
                            </div>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
              </div>


        <!-- ENDORSE -->
        <div class="ui vertical stripe stacked segment" id="enroll">
          <div class="ui center aligned grid container">
              <div class="row">
                <h3 class="ui header">
                  Become a QUESAYANO NOW <i class="exclamation icon"></i>
                </h3>
              </div>
              <div class="row">
                <p class="ui description">Come and join our community as we train our students excel in the fields of Science, Mathematics, and Technology.</p>
              </div>
              <div class="row">
                <a class="ui big green button" href="{% url 'main:admissions' %}">Enroll Now! <i class="ui angle right icon"></i></a>
              </div>
          </div>
        </div>
    </div>

{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/glider.js' %}"></script>
<script type="text/javascript">
  $(window).resize(function(){
    if (window.matchMedia('(max-width: 768px)').matches){
      $('#banner-text').show();
      $('#img-slides').hide();
    }
    else{
      $('#banner-text').hide();
      $('#img-slides').show();
    }
});

  new Glider(document.querySelector('.glider'), {
    slidesToShow: 1,
    slidesToScroll: 1,
    draggable: true,
    scrollLock: true,
    dots: '#dots',
    arrows : {
      prev : '.glider-prev',
      next: '.glider-next'
    },
  })
</script>
{% endblock %}

templates/main/lifeScience.html
{% extends 'base_2.html' %}
{% load staticfiles %}
{% block title %}
  Life Science
{% endblock %}
{% block main_content %}
	<div class="ui research segment">
	<center>
		<div class="text container">
			<div class="ui horizontal section divider" style="width:83%;"><h1>Research</h1></div>
		</div>
	</center>
	<br>

	<div class="ui container">
				<div class="ui relaxed divided items">
          {% for paper in research_paper %}
					<div class="item">
            <div class="ui small image">
              <img src="{% static 'img/avatar/tom.jpg' %}" alt="">
            </div>
						<div class="content">
							<a class="ui header" href="{% url 'main:life_science_detail' pk=paper.pk %}">{{ paper.title }}</a>
							<div class="meta">
								<p>
									{% for proponent in paper.proponents.all %}
		                {{ proponent.first_name|slice:"1"}}.{{ proponent.middle_name|slice:"1"}}. {{ proponent.last_name }},
		              {% empty %}
		                No Proponents
		              {% endfor %}
								</p>
								<p>Published on {{ paper.published_date|date:"d M, Y"}}</p>
							</div>
							<div class="description">
								{{ paper.abstract|truncatechars:200 }}
							</div>
							<div class="extra">
								<div class="ui label green">
									Applied / Physical
								</div>
								<a class="ui right floated orange button" href="{% url 'main:life_science_detail' pk=paper.pk %}">
                  Details
                  <i class="ui right arrow icon"></i>
								</a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>

	</div>

</div>
{% endblock %}

templates/main/lifeScience_detail.html
{% extends 'base_2.html'%}
{% block title %}
  Life Science
{% endblock %}
{% block main_content %}
  <div class="ui container segment">
    <a href="{% url 'main:life_science' %}" class="ui basic icon labeled button"><i class="ui angle double left icon"></i>All Papers</a>
    <div class="ui stackable celled grid">
      <div class="center aligned row">
        <div class="column">
          <h1 class="ui header">
            {{ object.title }}
          </h1>
        </div>
      </div>
      <div class="row">
        <div class="ten wide computer left floated sixteen wide tablet column">
          <div class="ui raised segment">
            <h2 class="ui header">Abstract</h2>
            <div class="ui divider"></div>
            {{ object.abstract }}
          </div>
        </div>
        <div class="six wide computer rigt floated sixteen wide tablet column">
          <div class="ui raised segment">
            <h2 class="ui header">Proponent{{ objects.proponents.all|pluralize}}</h2>
            <ul class="ui list">
              {% for proponent in object.proponents.all %}
              <li class="ui item">{{ proponent.first_name|slice:"1"}}. {{ proponent.middle_name|slice:"1" }}. {{proponent.last_name }}</li>
              {% endfor %}
            </ul>
            <h2 class="ui header">Published: </h2>
            <p class="ui description">{{ object.published_date|date:"M d, Y"}}</p>
            <div class="ui labeled button">
              <a href="{{ object.file.url }}" class="ui green icon button">Download</a>
              <div class="ui basic green label">
                <i class="ui download icon"></i>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/main/news.html
{% extends 'base_2.html' %}
{% block title %}
  News
{% endblock %}

{% block news %}
  active
{% endblock %}

{% block main_content %}
	<div class="news">
	<center>
		<div class="text container">
			<div class="ui horizontal section divider" style="width:83%;"><h1>News</h1></div>
		</div>
	</center>
	<br>
	<div class="ui container">
		<div class="ui relaxed divided items">
      {% if news %}
  			{% for news in news %}
        <div class="item">
          <div class="ui small image">
            <img src="{{ news.headline_image.url }}" alt="">
          </div>
          <div class="content">
            <a href="{% url 'main:news_detail' pk=news.pk %}" class="header">{{ news.headline|safe }}</a>
            <div class="description">
              {{ news.lead_text }}
            </div>
            <div class="meta">
              <p>
                Published {{ news.published_date|date:"M d, Y" }} by
                {% if news.author %}
                {{ news.author }} {% if news.author_additional_info %}-{{ news.author_additional_info }} {% endif %}
                {% else %}
                Anonymous
                {% endif %}
              </p>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div class="ui item">
          <h1 class="warning">No news yet</h1>
        </div>
      {% endif %}

		</div>
		<br><br>
	</div>
	</div>
{% endblock %}

templates/main/orgs.html
{% extends 'base_2.html' %}
{% block title %}
  Organizations
{% endblock %}

{% block org %}
  active
{% endblock %}

{% block main_content %}
	<div class="dimmed pusher">
    <div class="ui vertical stripe segment">
      <div class="ui container">
        <div class="ui horizontal section divider inverted">
          <h1 class="ui header">Organizations</h1>
        </div>
        <div class="ui relaxed divided items">
          {% for org in organizations %}
            <div class="ui item">
              <div class="ui small image">
                <img src="{{ org.logo.url }}" alt="">
              </div>
              <div class="content">
                <a href="{% url 'main:organization_details' pk=org.pk %}" class="ui header">
                  {{ org.name }}
                </a>
                <div class="meta">
                  {{ org.category }}
                </div>
                <div class="description">
                  {{ org.description|truncatechars:100 }}
                </div>
                <div class="other description">
                  <a href="{% url 'main:organization_details' pk=org.pk %}" class="ui inverted green button">Details</a>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
</div>
{% endblock %}