arachnid/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('staff/', include('staff.urls', namespace="staff")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('albums/', include('album.urls', namespace='album'))
    #path('albums/', include('album.urls', namespace="album"))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    path('admissions',
        views.AdmissionView.as_view(),
        name="admissions"),

    path('news',
        views.NewsView.as_view(),
        name="news"),

    path('news/details/<int:pk>', views.NewsDetailView.as_view(),
        name="news_detail"),

    path('organizations',views.OrganizationListView.as_view(),name="organizations"),
    path('organizations/details/<int:pk>', views.OrganizationDetailView.as_view(), name="organization_details"),


    path('life_science', views.LifeListView.as_view(), name="life_science"),
    path('life_science/details/<int:pk>', views.LifeDetailView.as_view(),name="life_science_detail"),

    path('applied_science', views.AppliedListView.as_view(),name="applied_science"),
    path('applied_science/details/<int:pk>', views.AppliedDetailView.as_view(),name="applied_science_detail"),


    path('about',
        views.AboutView.as_view(),
        name="about"
    ),

    path('faqs',
        views.FAQsView.as_view(),
        name="faqs"
    )
]

staff/urls.py
from django.urls import path, include
from . import views
from album import views as album_views
from django.contrib.auth import views as auth_view

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcements'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name="create_announcement"),
    path('announcements/view/<int:pk>/', views.view_file, name="view_file"),

    path('news/', views.NewsListView.as_view(), name="news"),
    path('news/create/', views.NewsCreateView.as_view(), name="create_news"),
    path('news/update/<int:pk>/', views.NewsUpdateView.as_view(), name="update_news"),
    path('news/delete/<int:pk>/', views.NewsDeleteView.as_view(), name="delete_news"),
    path('news/publish/<int:pk>/', views.publish_news, name="publish"),

    path('organizations/', views.OrganizationListView.as_view(), name="organizations"),
    path('organizations/create/', views.OrganizationCreateView.as_view(), name="create_organization"),
    path('organizations/delete/<int:pk>/', views.OrganizationDeleteView.as_view(), name="delete_organization"),
    path('organizations/update/<int:pk>/', views.OrganizationUpdateView.as_view(), name="update_organization"),
    path('organization/details/<int:pk>/', views.OrganizationDetailView.as_view(), name="organization_detail"),

    path('research/', views.ResearchListView.as_view(), name="research"),
    path('research/create/', views.ResearchCreateView.as_view(), name="create_research"),
    path('research/delete/<int:pk>/', views.ResearchDeleteView.as_view(), name="delete_research"),
    path("research/update/<int:pk>/", views.ResearchUpdateView.as_view(), name="update_research"),
    path("research/details/<int:pk>/", views.ResearchDetailView.as_view(), name="research_detail"),
    path('research/details/<int:pk>/add_proponent/', views.add_proponent_to_research, name="add_proponent_to_research"),

    path('accounts/login/', auth_view.login, name="login"),
    path('accounts/logout/', auth_view.logout, name="logout", kwargs={'next_page': '/'}),

    # For the organization hr
    path('organizations/<organization>/hr/', views.OrganizationHRListView.as_view(), name="organization_hr_list"),
    path('organizations/<organization>/hr/create', views.OrganizationHRCreateView.as_view(), name="organization_hr_create"),
    path('organizations/<organization>/hr/delete/<int:pk>/', views.OrganizationHRDeleteView.as_view(), name="organization_hr_delete"),
    path('organizations/<organization>/hr/update/<int:pk>/', views.OrganizationHRUpdateView.as_view(), name="organization_hr_update"),
    path('organizations/<organization>/hr/details/<int:pk>/', views.OrganizationHRDetailView.as_view(), name="organization_hr_detail"),

    # for the albums section
    path('albums/', album_views.AlbumListView.as_view(), name="albums"),
    path('albums/create', album_views.AlbumCreateView.as_view(), name="create_album"),
    path('albums/delete/<int:pk>/', album_views.AlbumDeleteView.as_view(), name="album_delete"),
    path('albums/<slug:album>/photos/delete/<int:pk>/', album_views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('albums/<slug:album>/photos', album_views.PhotosListView.as_view(), name="photos"),
    path('albums/<slug:album>/photos/upload', album_views.PhotoUploadView.as_view(), name="upload_photo")

]

staff/forms.py
from django import forms
from . import models
from django.core import validators
class AnnouncementForm(forms.ModelForm):
    class Meta:
        model = models.Announcement
        fields = ('title', 'description', 'file')
        widgets = {
        	'title': forms.TextInput(),
        	'description': forms.Textarea(),
        	'file': forms.FileInput()
        }

class NewsForm(forms.ModelForm):
    class Meta:
        model = models.News
        fields = ('author', 'author_additional_info', 'lead_text', 'headline', 'headline_image', 'cover_photo', 'body_text', 'other_image', 'other_image_label')
        widgets = {
            'author': forms.TextInput(attrs={'placeholder': 'Name of the author (not required)'}),

            'author_additional_info': forms.TextInput(attrs={'class': 'textinputclass'}),

            'lead_text': forms.Textarea(attrs={'placeholder': 'Write here the lead paragraph/sentence', }),

            'headline': forms.Textarea(attrs={'class': 'editable medium-editor-textarea', 'placeholder': 'Write headline'}),

            'body_text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),

            'other_image_label': forms.TextInput(attrs={'placeholder': 'Write label for other image'})
        }
    
        

LEVEL = (
    ("Main", "Main"),
    ("Core Subject", "Core Subject"),
    ("Social Science", "Social Science"),
    ("Music and Arts", "Music and Arts"),
)

class OrganizationForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name of Organization'}),
            'category': forms.Select(choices=LEVEL),
            'acronym': forms.TextInput(attrs={'placeholder': 'E.g. RobITech, YAG'}),
            'description': forms.Textarea(),
        }

CATEGORY_CHOICES = (
    ("Applied", "Applied Science"),
    ("Life", "Life Science")
)

# For organization HR
class OrganizationHRForm(forms.ModelForm):
    class Meta:
        model = models.OrganizationOfficer
        exclude  = ('organization', )
        widgets = {
            'adviser': forms.TextInput(),
            'president': forms.TextInput(),
            'vice_president': forms.TextInput(),
            'secretary': forms.TextInput(),
            'treasurer': forms.TextInput(),
            'auditor': forms.TextInput(),
            'pio': forms.TextInput(),
            'g7_rep': forms.TextInput(),
            'g8_rep': forms.TextInput(),
            'g9_rep': forms.TextInput(),
            'g10_rep': forms.TextInput(),
            'g11_rep': forms.TextInput(),
            'g12_rep': forms.TextInput(),
        }

class ResearchForm(forms.ModelForm):
    class Meta:
        model = models.ResearchPaper
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(),
            'abstract': forms.Textarea(),
            'published_date': forms.DateInput(),
            'category': forms.Select(choices=CATEGORY_CHOICES)
        }

class ResearchProponentForm(forms.ModelForm):
    class Meta:
        model = models.ResearchProponent
        fields = ('first_name', 'middle_name', 'last_name')

staff/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import TemplateView, CreateView, UpdateView, ListView, DetailView, DeleteView, FormView
from django.urls import reverse_lazy, reverse
from .forms import AnnouncementForm, NewsForm, OrganizationForm, ResearchForm, ResearchProponentForm, OrganizationHRForm
from .models import Announcement, News, Organization, ResearchPaper, ResearchProponent, OrganizationOfficer
from django.contrib.auth.mixins import LoginRequiredMixin
from reportlab.pdfgen import canvas
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404, HttpResponseRedirect


class IndexView(LoginRequiredMixin, TemplateView):
    redirect_field_name='staff/index.html'
    template_name = 'staff/index.html'

class AnnouncementListView(LoginRequiredMixin, ListView):
    redirect_field_name='staff/index.html'
    model = Announcement
    context_object_name= 'announcements'
    def get_queryset(self):
        return Announcement.objects.order_by('-date_created')

class AnnouncementCreateView(LoginRequiredMixin, CreateView):
    redirect_field_name='staff/index.html'
    model = Announcement
    form_class = AnnouncementForm



def view_file(request, pk):
    from arachnid.settings import BASE_DIR
    announcement = get_object_or_404(Announcement, pk=pk)
    file = BASE_DIR + announcement.file.url
    f = open(file, 'w+b')
    f.seek(0)
    pdf = f.read()
    f.close()
    return HttpResponse(file, 'application/pdf')
    #response['Content-Disposition'] = 'attachment; filename="{}.pdf"'.format(announcement.file)

    #p = canvas.Canvas(response)
    #p.showPage()
    #p.save()
    #return response

# ------------------- News Views ------------------- #

class NewsListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'staff/index.html'
    model = News
    context_object_name = "news"
    def get_queryset(self):
        return News.objects.order_by('-created_date')

class NewsCreateView(LoginRequiredMixin, CreateView):
    redirect_field_name = 'staff/news_list.html'
    model = News
    form_class = NewsForm

class NewsUpdateView(LoginRequiredMixin, UpdateView):
    redirect_field_name = 'staff/news_list.html'
    model = News
    form_class = NewsForm
    pk_url_kwarg = 'pk'

class NewsDeleteView(LoginRequiredMixin, DeleteView):
    model = News
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('staff:news')

@login_required
def publish_news(request, pk):
    news = get_object_or_404(News, pk=pk)
    news.publish()
    return redirect('staff:index')


# ------------------- Organization Views ------------------- #

class OrganizationListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'staff/index.html'
    model = Organization
    context_object_name = 'organizations'
    def get_queryset(self):
        return Organization.objects.order_by('name')

class OrganizationCreateView(LoginRequiredMixin, CreateView):
    redirect_field_name = 'staff/index.html'
    model = Organization
    form_class = OrganizationForm

class OrganizationUpdateView(LoginRequiredMixin, UpdateView):
    redirect_field_name = 'staff/index.html'
    model = Organization
    form_class = OrganizationForm
    pk_url_kwarg = 'pk'

class OrganizationDeleteView(LoginRequiredMixin, DeleteView):
    model = Organization
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('staff:organizations')

class OrganizationDetailView(LoginRequiredMixin, DetailView):
    model = Organization
    context_object_name = "organization"
    pk_url_kwarg = 'pk'

# ----------- For the organization officers --------- #

class OrganizationHRListView(LoginRequiredMixin, ListView):
    template_name = 'staff/organization_hr_list.html'
    redirect_field_name = 'staff/index.html'
    model = OrganizationOfficer
    context_object_name = 'human_resource'
    def get_queryset(self):
        organization = get_object_or_404(Organization, name=self.kwargs.get('organization'))
        print(organization.id)
        return organization.officers.all()

class OrganizationHRCreateView(LoginRequiredMixin, CreateView):
    redirect_field_name = 'staff/index.html'
    template_name = 'staff/organization_hr_form.html'
    model = OrganizationOfficer
    form_class = OrganizationHRForm
    success_url = reverse_lazy('staff:organizations')
    def form_valid(self, form):
        organization = get_object_or_404(Organization, name=self.kwargs.get('organization'))
        officer = form.save(commit=False)
        officer.organization = organization
        officer.save()
        return HttpResponseRedirect(reverse('staff:organizations'))


class OrganizationHRUpdateView(LoginRequiredMixin, UpdateView):
    redirect_field_name = 'staff/index.html'
    template_name = 'staff/organization_hr_form.html'
    model = OrganizationOfficer
    form_class = OrganizationHRForm
    pk_url_kwarg = 'pk'

class OrganizationHRDeleteView(LoginRequiredMixin, DeleteView):
    model = OrganizationOfficer
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('staff:organizations')

class OrganizationHRDetailView(LoginRequiredMixin, DetailView):
    template_name = 'staff/organization_hr_detail.html'
    model = OrganizationOfficer
    context_object_name = "organization"
    pk_url_kwarg = 'pk'


# ------------------- Research Views ------------------- #

class ResearchListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'staff/index.html'
    model = ResearchPaper
    context_object_name = "research_papers"
    def get_queryset(self):
        return ResearchPaper.objects.order_by('-title')

class ResearchCreateView(LoginRequiredMixin, CreateView):
    redirect_field_name = 'staff/index.html'
    model = ResearchPaper
    form_class = ResearchForm

class ResearchUpdateView(LoginRequiredMixin, UpdateView):
    redirect_field_name = 'staff/index.html'
    model = ResearchPaper
    form_class = ResearchForm
    pk_url_kwarg = 'pk'

class ResearchDeleteView(LoginRequiredMixin, DeleteView):
    model = ResearchPaper
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('staff:research')

class ResearchDetailView(LoginRequiredMixin, DetailView):
    model = ResearchPaper
    context_object_name = 'research_paper'
    pk_url_kwarg = 'pk'

@login_required
def add_proponent_to_research(request, pk):
    research_paper = get_object_or_404(ResearchPaper, pk=pk)
    if request.method == "POST":
        form = ResearchProponentForm(request.POST)
        if form.is_valid():
            proponent = form.save(commit=False)
            proponent.research = research_paper
            proponent.save()
            return redirect('staff:research_detail', pk=research_paper.pk)
    else:
        form = ResearchProponentForm()
        return render(request, 'staff/researchpaperproponents_form.html', {'form': form})

templates/staff/announcement_form.html
{% extends 'staff/base_staff.html' %}

{% block main_content %}
  <div class="ui container segment">
    <form class="ui equal width form" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="ui field">
        <label for="title">Title for the announcement</label>
        {{ form.title }}
      </div>
      <div class="ui field">
        <label for="description">Announcement description</label>
        {{ form.description }}
      </div>
      <div class="ui field">
        <label for="file">OPTIONAL: File attachment</label>
        {{ form.file }}
      </div>      
      <div class="ui field">
        <input type="submit" value="Post" class="ui green button">
      </div>
    </form>
  </div>

{% endblock %}

templates/staff/announcement_list.html
{% extends 'staff/base_staff.html' %}

{% block announcement %}
	active
{% endblock %}
{% block main_content %}
	<div class="ui grid segments">
		<div class="row">
			<div class="four wide right floated right aligned column">
				<a href="{% url 'staff:create_announcement' %}" class="ui orange button">Create Announcement</a>
			</div>
		</div>
		<div class="row">
			<div class="column">
				<div class="ui segment">
			    <table class="ui celled two column table">
			    	{% for announcement in announcements %}
			    	<tr>
			    		<td>
			    			{{ announcement.title }}
			    		</td>
			    		<td>
								{% if announcement.file %}
			    			<a href="{{ announcement.file.url }}"><i class="ui file icon"></i> {{ announcement.file.url }}</a>
								{% else %}
								No file attached
								{%endif%}
			    		</td>
			    	</tr>
			    	{% endfor %}
			    </table>

			  </div>
			</div>
		</div>
	</div>
{% endblock %}

templates/staff/index.html
{% extends 'staff/base_staff.html'%}

{% block main_content %}

  <div class="ui container segment">
    <table class="ui table">
      <thead>
        <th>Object</th>
        <th>Hit count</th>
      </thead>
      <tbody>
        <td>
          Announcement
        </td>
        <td>
        </td>
      </tbody>
    </table>
  </div>
{% if files %}
  {% for file in files %}
    <a href="{{ file.file.url }}">{{ file.file }}</a>
    <h1>{{ file.url }}</h1>
  {% endfor %}
{% else %}
<h1>Error</h1>
{% endif %}
{% endblock %}

templates/staff/news_confirm_delete.html
{% extends 'staff/base_staff.html' %}

{% block main_content %}
  <div class="ui segment">
    <form class="ui form" method="post">
      {% csrf_token %}
      <h3 class="ui header red">Are you sure you want to delete {{ object|safe }}?</h3>
      <input type="submit" value="Confirm" class="ui danger button">
    </form>
  </div>
{% endblock %}

templates/staff/news_list.html
{% extends 'staff/base_staff.html' %}

{% block title %}
  List of News
{% endblock %}

{% block news %}
  active
{% endblock %}

{% block main_content %}
  <div class="ui raised segment">
    <div class="ui grid">
      <div class="row">
        <div class="center aligned column">
          <h1 class="ui header">List of all news</h1>
        </div>
      </div>
      <div class="row">
        <a href="{% url 'staff:create_news' %}" class="ui orange button">Add News</a>
      </div>
      <div class="ui row stackable center aligned two column internally celled grid">
        <div class="ui eight wide computer sixteen wide tablet column">
          <div class="row">
            <div class="column">
              <h4 class="ui header">Unpublished News</h4>
            </div>
          </div>
          <table class="ui three column celled table">
            <thead>
              <tr>
                <th>Author</th>
                <th>Headline</th>
              </tr>
            </thead>
            <tbody>
              {% for news in news %}
              <tr>
                {% if not news.published_date %}
                <td>
                  {% if news.author %} {{ news.author }} {% else %} None {% endif %}
                </td>
                <td>
                  {{ news.headline|safe|truncatechars:15 }}
                </td>
                <td>
                  <div class="ui buttons">
                      <a href="{% url 'staff:publish' pk=news.pk %}" class="ui green button">Publish</a>
                      <div class="or"></div>
                      <a href="{% url 'staff:delete_news' pk=news.pk %}" class="ui red button">Delete</a>
                  </div>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="ui eight wide computer sixteen wide tablet column">
          <div class="row">
            <div class="column">
              <h4 class="ui header">Published News</h4>
            </div>
          </div>
          <table class="ui three column celled table">
            <thead>
              <tr>
                <th>Author</th>
                <th>Headline</th>
              </tr>
            </thead>
            <tbody>
              {% for news in news %}
              <tr>
                {% if news.published_date %}
                <td>
                  {% if news.author %} {{ news.author }} {% else %} None {% endif %}
                  {{ news.pk }}
                </td>
                <td>
                  {{ news.headline|safe|truncatechars:10 }}
                </td>
                <td>
                  <div class="ui buttons">
                      <a href="{% url 'staff:update_news' pk=news.pk %}" class="ui orange button">Update</a>
                      <div class="or"></div>
                      <a href="{% url 'staff:delete_news' pk=news.pk %}" class="ui red button">Delete</a>
                  </div>
                </td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/staff/organization_confirm_delete.html
{% extends 'staff/base_staff.html' %}
{% block title %}
  Cofirm delete - {{ object }}
{% endblock %}
{% block main_content %}
<div class="ui contaienr">
  <div class="ui segment">
    <form class="ui form" method="post">
      {% csrf_token %}
      <h3 class="ui header">Are you sure you want to delete {{ object }}?</h3>
      <div class="ui grid">
        <div class="ui right floated column">
          <button type="submit" name="button" class="ui red icon labeled button"><i class="ui delete icon"></i>Confirm</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

templates/staff/organization_detail.html
{% extends 'staff/base_staff.html' %}
{% load staticfiles %}
{% block title %}
  Details - {{ organization.name }}
{% endblock %}
{% block organization %}
  active
{%endblock%}
{% block main_content %}
  <div class="ui segment">
    <div class="ui container">
      <div class="ui celled grid">
        <div class="row">
          <div class="right floated three wide column">
              <img src="{{ organization.logo.url }}" alt="logo" width="100px" height="100px">
          </div>
        </div>
        <div class="row">
          <div class="column">
            <h2>Name: {{ organization.name }}</h2>
            <h2>Acronym: {{ organization.acronym }}</h2>
          </div>
        </div>
        
        {% if org %}
        <div class="row">
          <table class="ui table">
            <thead>
              <th>Name</th>
              <th>Position</th>
              <th>Picture</th>
            </thead>
            <tbody>
              <tr>
                <td>
                  {{ organization.adviser }}
                </td>
                <td>
                  Adviser
                </td>
                <td>
                  {% if organization.adviser_picture %}
                  <img src="{{ organization.adviser_picture.url }}" alt="Adviser" width="100px" height="100px">
                  {% else %}
                  <img src="{% static 'img/avatar/tom.jpg' %}" alt="Adviser" width="100px" height="100px">
                  {% endif %}
                </td>
              </tr>
              <tr>
                <td>
                  {{ organization.president }}
                </td>
                <td>
                  President
                </td>
                <td>
                  {% if organization.pres_picture %}
                  <img src="{{ organization.pres_picture.url }}" alt="Adviser" width="100px" height="100px">
                  {% else %}
                  <img src="{% static 'img/avatar/tom.jpg' %}" alt="Adviser" width="100px" height="100px">
                  {% endif %}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        {% endif %}
        <div class="row">
          <div class="ui six wide right floated column">
            <div class="ui buttons">
              <a href="{% url 'staff:update_organization' pk=organization.pk %}" class="ui orange button">Update Information</a>
              <div class="or"></div>
              <a href="{% url 'staff:delete_organization' pk=organization.pk %}" class="ui red button">Delete Organization</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/staff/organization_form.html
{% extends 'staff/base_staff.html' %}

{% block organization %}
  active
{% endblock %}
{% block title %}Organizations{% endblock %}
{% block main_content %}
  <div class="ui container">
    <div class="ui segment">
      {% if object %}
      <div class="ui orange right ribbon label">
        Updating an organization
      </div>
      {% else %}
      <div class="ui red right ribbon label">
        New Organization
      </div>
      {% endif %}
      <div class="ui attached segment">
        {% if object %}
          <h3 class="ui header">Update {{ object }}</h3>
        {% else %}
          <h3 class="ui header">Create A New Organization</h3>
        {% endif %}
        {% if form.errors %}
        <div class="ui warning message">
          {{ form.errors }}
        </div>
        {% endif %}
      </div>
      <form class="ui equal width attached fluid segment form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ui fields">
          <div class="ui field">
            <label for="name">Name of Organization</label>
            {{ form.name }}
          </div>
          <div class="ui field">
            <label for="acronym">Acronym</label>
            {{ form.acronym }}
          </div>
          <div class="ui field">
            <label for="">Logo</label>
            {{ form.logo }}
          </div>
        </div>
        <div class="ui field">
          <label for="description">Description</label>
          {{ form.description }}
        </div>
        {% if object %}
        <input type="submit" value="Update" class="ui orange inverted button">
        {% else %}
        <input type="submit" value="Create" class="ui green inverted button">
        {% endif %}
      </form>
    </div>
  </div>
{% endblock %}

templates/staff/organization_hr_form.html
{% extends 'staff/base_staff.html' %}

{% block organization %}
  active
{% endblock %}
{% block title %}Organizations{% endblock %}
{% block main_content %}
  <div class="ui container">
    <div class="ui segment">
      {% if object %}
      <div class="ui orange right ribbon label">
        Updating Officers
      </div>
      {% else %}
      <div class="ui red right ribbon label">
        New Officers
      </div>
      {% endif %}
      <div class="ui attached segment">
        {% if object %}
          <h3 class="ui header">Update {{ object }}</h3>
        {% else %}
          <h3 class="ui header">Create A New Batch of Officers</h3>
        {% endif %}
        {% if form.errors %}
        <div class="ui warning message">
          {{ form.errors }}
        </div>
        {% endif %}
      </div>
      <form class="ui equal width attached fluid segment form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        {% if object %}
        <input type="submit" value="Update" class="ui orange inverted button">
        {% else %}
        <input type="submit" value="Create" class="ui green inverted button">
        {% endif %}
      </form>
    </div>
  </div>
{% endblock %}

templates/staff/organization_list.html
{% extends 'staff/base_staff.html' %}

{% block organization %}
  active
{% endblock %}
{% block title %}Organizations{% endblock %}
{% block main_content %}

  <div class="ui container">
    <div class="ui segment">
      <a href="{% url 'staff:create_organization' %}" class="ui green icon labeled button"><i class="ui plus icon"></i>Create Organization</a>
      <table class="ui celled three column table">
        <thead>
          <th>Name</th>
          <th>Action</th>
          <th>Staffs and HR</th>
        </thead>
        <tbody>
          {% for org in organizations %}
          <tr>
            <td>
              {{ org.name }}
            </td>
            <td>
              <div class="ui buttons">
                <a href="{% url 'staff:delete_organization' pk=org.pk%}" class="ui red button">Delete</a>
                <a href="{% url 'staff:update_organization' pk=org.pk%}" class="ui orange button">Update</a>
                <a href="{% url 'staff:organization_detail' pk=org.pk %}" class="ui blue button">Details</a>
              </div>
            </td>
            <td>
              <div class="ui buttons">
                <a href="{% url 'staff:organization_hr_list' organization=org.name%}" class="ui blue button">Details</a>
                <a href="{% url 'staff:organization_hr_create' organization=org.name%}" class="ui green button">Add officers</a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

{% endblock %}

templates/staff/researchpaper_form.html
{% extends 'staff/base_staff.html' %}

{% block title %}
  {% if object %}
  Update Research Paper
  {% else %}
  Create Research Paper
  {% endif %}
{% endblock %}

{% block research %}
  active
{% endblock %}

{% block main_content %}
  <div class="ui container">
    <div class="ui segment">
      <div class="ui attached segment">
        {% if object or form.errors %}
        <h2 class="ui header">Update a Research</h2>
        {{ form.errors }}
        {% else %}
        <h2 class="ui header">Create a Research</h2>
        {% endif %}
      </div>
      <form class="ui attached segment form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="ui field">
          <label for="title">Title of the Study</label>
          <input type="text" name="title" placeholder="E.g. The Utilization of Malunggay as Nuclear Bomb">
        </div>
        <div class="ui field">
          <label for="published_date">Date of Publication</label>
          <input type="date" name="published_date">
        </div>
        <div class="ui field">
          <label for="file">File (in pdf)</label>
          {{ form.file }}
        </div>
        <div class="ui field">
          <label for="category">Category</label>
          {{ form.category }}
        </div>
        <div class="ui field">
          <label for="abstact">Abstract</label>
          {{ form.abstract }}
        </div>
        {% if object %}
        <input type="submit" value="Update" class="ui orange button">
        {% else %}
        <input type="submit" value="Create" class="ui green button">
        {% endif %}
      </form>
    </div>
  </div>
{% endblock %}

templates/staff/upload.html
{% if form.errors %}
  <h1 style="color:red">{{ form.errors }}</h1>
{% endif %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Upload">
</form>