album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('', views.AlbumTemplateView.as_view(), name="albums"),
    path('lists/', views.AlbumList.as_view(), name="albums_list"),
    path('<slug:album>/photos', views.PhotoTemplateView.as_view(), name="photos_list"),
    path('<slug:album>/photos/list/', views.PhotoList.as_view(), name="photos")
]

arachnid/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('staff/', include('staff.urls', namespace="staff")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('albums/', include('album.urls', namespace='album'))
    #path('albums/', include('album.urls', namespace="album"))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    path('admissions',
        views.AdmissionView.as_view(),
        name="admissions"),

    path('news',
        views.NewsView.as_view(),
        name="news"),

    path('news/details/<int:pk>', views.NewsDetailView.as_view(),
        name="news_detail"),

    path('organizations',views.OrganizationListView.as_view(),name="organizations"),
    path('organizations/details/<int:pk>', views.OrganizationDetailView.as_view(), name="organization_details"),


    path('life_science', views.LifeListView.as_view(), name="life_science"),
    path('life_science/details/<int:pk>', views.LifeDetailView.as_view(),name="life_science_detail"),

    path('applied_science', views.AppliedListView.as_view(),name="applied_science"),
    path('applied_science/details/<int:pk>', views.AppliedDetailView.as_view(),name="applied_science_detail"),


    path('about',
        views.AboutView.as_view(),
        name="about"
    ),

    path('faqs',
        views.FAQsView.as_view(),
        name="faqs"
    )
]

staff/urls.py
from django.urls import path, include
from . import views
from album import views as album_views
from django.contrib.auth import views as auth_view

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcements'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name="create_announcement"),
    path('announcements/view/<int:pk>/', views.view_file, name="view_file"),

    path('news/', views.NewsListView.as_view(), name="news"),
    path('news/create/', views.NewsCreateView.as_view(), name="create_news"),
    path('news/update/<int:pk>/', views.NewsUpdateView.as_view(), name="update_news"),
    path('news/delete/<int:pk>/', views.NewsDeleteView.as_view(), name="delete_news"),
    path('news/publish/<int:pk>/', views.publish_news, name="publish"),

    path('organizations/', views.OrganizationListView.as_view(), name="organizations"),
    path('organizations/create/', views.OrganizationCreateView.as_view(), name="create_organization"),
    path('organizations/delete/<int:pk>/', views.OrganizationDeleteView.as_view(), name="delete_organization"),
    path('organizations/update/<int:pk>/', views.OrganizationUpdateView.as_view(), name="update_organization"),
    path('organization/details/<int:pk>/', views.OrganizationDetailView.as_view(), name="organization_detail"),

    path('research/', views.ResearchListView.as_view(), name="research"),
    path('research/create/', views.ResearchCreateView.as_view(), name="create_research"),
    path('research/delete/<int:pk>/', views.ResearchDeleteView.as_view(), name="delete_research"),
    path("research/update/<int:pk>/", views.ResearchUpdateView.as_view(), name="update_research"),
    path("research/details/<int:pk>/", views.ResearchDetailView.as_view(), name="research_detail"),
    path('research/details/<int:pk>/add_proponent/', views.add_proponent_to_research, name="add_proponent_to_research"),

    path('accounts/login/', auth_view.login, name="login"),
    path('accounts/logout/', auth_view.logout, name="logout", kwargs={'next_page': '/'}),

    # For the organization hr
    path('organizations/<organization>/hr/', views.OrganizationHRListView.as_view(), name="organization_hr_list"),
    path('organizations/<organization>/hr/create', views.OrganizationHRCreateView.as_view(), name="organization_hr_create"),
    path('organizations/<organization>/hr/delete/<int:pk>/', views.OrganizationHRDeleteView.as_view(), name="organization_hr_delete"),
    path('organizations/<organization>/hr/update/<int:pk>/', views.OrganizationHRUpdateView.as_view(), name="organization_hr_update"),
    path('organizations/<organization>/hr/details/<int:pk>/', views.OrganizationHRDetailView.as_view(), name="organization_hr_detail"),

    # for the albums section
    path('albums/', album_views.AlbumListView.as_view(), name="albums"),
    path('albums/create', album_views.AlbumCreateView.as_view(), name="create_album"),
    path('albums/delete/<int:pk>/', album_views.AlbumDeleteView.as_view(), name="album_delete"),
    path('albums/<slug:album>/photos/delete/<int:pk>/', album_views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('albums/<slug:album>/photos', album_views.PhotosListView.as_view(), name="photos"),
    path('albums/<slug:album>/photos/upload', album_views.PhotoUploadView.as_view(), name="upload_photo")

]

album/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

from io import BytesIO
from PIL import Image
from django.core.files import File

from django.core.exceptions import ValidationError

def compress(image):
    im = Image.open(image)
    # create a BytesIO object
    im_io = BytesIO() 
    # save image to BytesIO object
    im.save(im_io, 'JPEG', quality=70) 
    # create a django-friendly Files object
    new_image = File(im_io, name=image.name)
    return new_image

# Create your models here.
class Album(models.Model):
    title = models.CharField(max_length=120, unique=True)
    description = models.CharField(max_length=300)
    date = models.DateTimeField(default=timezone.now)
    slug = models.SlugField(allow_unicode=True, unique=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    def __str__(self):
        return self.title

def image_upload_method(instance, filename):
    return 'albums/{album}/{photo}'.format(album=instance.album.slug, photo=filename)

class Photo(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE, blank=True, null=True, related_name="photos")
    file = models.ImageField(upload_to=image_upload_method, blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.file.name

    def save(self, *args, **kwargs):
        try:
            new_image = compress(self.file)
            self.file = new_image
        except IOError as error:
            print(error)
            raise ValidationError('Invalid Image Format')
        return super().save(*args, **kwargs)

album/forms.py
from django import forms
from .models import Album, Photo

class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('title','description')

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('file',)

album/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import JsonResponse
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from django.views import View
from django.http import JsonResponse # For the image view
from django.contrib.auth.mixins import LoginRequiredMixin # For authentication
from .forms import PhotoForm, AlbumForm
from .models import Photo, Album
from pprint import pprint
from django.core import serializers
import json

import os # For returning the appropriate file name, not the directory + filename
# Create your views here.


# For the public

class AlbumTemplateView(TemplateView):
    template_name = 'album/albums.html'

class AlbumList(View):
    def get(self, *args, **kwargs):
        albums = Album.objects.order_by('-date')
        data = []
        for album in albums:
            alb = {}
            photo = get_list_or_404(Photo, album=album)
            alb['name'] = album.title
            alb['slug'] = album.slug
            alb['date_created'] = album.date
            alb['description'] = album.description
            alb['first_photo'] = photo[0].file.url
            data.append(alb)

        print(data)
        #pprint(json.dumps(albums_serialized))
        return JsonResponse({'data' : data})

class PhotoTemplateView(TemplateView):
    template_name = 'album/photos.html'
    def get(self, *args, **kwargs):
        #print(args)
        print(kwargs['album'])
        return super().get(*args, **kwargs)

class PhotoList(View):
    def get(self, *args, **kwargs):
        photos = get_list_or_404(Photo)
        data = []
        for photo in photos:
            if photo.album.slug == kwargs['album']:
                image = {}
                image['album_description'] = photo.album.description
                image['album'] = photo.album.pk
                image['album_title'] = photo.album.title
                image['file'] = photo.file.url
                image['date'] = photo.album.date.strftime('%Y-%m-%d %H:%M:%S %Z')
                data.append(image)
        #pprint(data)
        return JsonResponse({'data': data})
        #return ("Hello world")

# For the admin panel
class AlbumCreateView(LoginRequiredMixin, CreateView):
    template_name = 'album/album_create.html'
    model = Album
    form_class = AlbumForm
    success_url = reverse_lazy('staff:albums')

class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('staff:albums')

class AlbumListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'album/albums.html'

    model = Album
    context_object_name = 'albums'
    def get_queryset(self):
        return Album.objects.order_by('-date')

class PhotosListView(LoginRequiredMixin, ListView):
    redirect_field_name = 'album/albums.html'
    template_name = 'album/photo_list.html'
    model = Photo
    context_object_name = 'photos'
    def get_queryset(self):
        album = get_object_or_404(Album, slug=self.kwargs.get('album'))
        data = {'album_slug': album.slug, 'photos': album.photos.all()}
        return data

class PhotoUploadView(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        photoForm = PhotoForm(self.request.POST, self.request.FILES)
        if photoForm.is_valid():
            photo = photoForm.save(commit=False)
            album = get_object_or_404(Album, slug=self.kwargs.get('album'))
            photo.album = album
            photo.save()
            data = {'is_valid': True, 'url' : photo.file.url, 'name' : os.path.split(photo.file.name)[1] }
        else:
            data = {'is_valid' : False}

        return JsonResponse(data)

class PhotoDeleteView(LoginRequiredMixin, DeleteView):
    model = Photo
    pk_url_kwarg = 'pk'
    url = ''
    success_url = reverse_lazy('staff:albums') ## TODO: change the returned url
                                                # and redirect back to the
                                                # photos page
    def delete(self, *args, **kwargs):
        print("O oh!! someone deleted a photo")
        return super().delete(*args, **kwargs)

album/templates/album/album_confirm_delete.html
{% extends 'staff/base_staff.html' %}
{% block main_content %}
  <div class="ui container">
    <div class="ui segment">
      <form class="ui form" method="post">
        {% csrf_token %}
        <h3>Are you sure you want to delete <i>{{ object }}?</i></h3>
        <div class="ui buttons">
          <a href="{% url 'staff:albums' %}" class="ui green button">No</a>
          <input type="submit" value="Confirm" class="ui red button">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

album/templates/album/album_create.html
{% extends 'staff/base_staff.html' %}
{% block main_content %}
  <div class="ui raised segment">
    <form class="ui form" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Create" class="ui green button">
    </form>
  </div>
{% endblock %}

album/templates/album/album_list.html
{% extends 'staff/base_staff.html' %}
{% block album %}
  active
{% endblock %}
{% block main_content %}
  <div class="ui raised segment">
    <div class="ui grid">
      <div class="row">
        <div class="column">
          <h1 class="ui centered header">List of Albums Posted</h1>
          <a href="{% url 'staff:create_album' %}" class="ui orange button">Create an Album</a>
        </div>
      </div>
      <div class="row">
        <div class="column">
          <table class="ui two column celled table">
            <thead>
              <tr>
                <td>Album</td>
                <td>Action</td>
              </tr>
            </thead>
            <tbody>
              {% for album in albums %}
              <tr>
                  <td>{{ album.title }}</td>
                  <td>
                    <a href="{% url 'staff:photos' album=album.slug %}" class="ui green button">Details</a>
                    <a href="{% url 'staff:album_delete' pk=album.pk %}" class="ui red button">Delete</a>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

album/templates/album/albums.html
{% extends 'base_2.html' %}
{% block album %}
active
{% endblock album %}
{% block main_content %}
<div class="ui container">
  <div class="ui vertical stripe stackable segment">
    <div class="ui horizontal section divider inverted">
      <h1 class="ui header">Albums</h1>
    </div>
    <div class="ui three stackable special cards" id="album">

    </div>
  </div>
</div>

{% endblock %}
{% block javascript %}
<script type="text/javascript">
  // TODO: move the following scripts to an external source
  // Just to implement the '{}.format' method in python
  $(document).ready(function(){
    String.prototype.format = function() {
        a = this;
        for (k in arguments) {
          a = a.replace("{" + k + "}", arguments[k])
        }
        return a
      }
    function generateAlbum(value, index, array){
      let date_created = value['date_created']
      let album_name = value['name']
      let album_description = value['description']
      let photo = value['first_photo']
      var album_slug = value['slug']
      console.log('album_slug')
      var url = album_slug +"/photos"
      console.log(url)
      d = '<div class="ui card"><div class="blurring dimmable image"><div class="ui blurring dimmer"><div class="content"><div class="center"><a class="ui inverted button" href="{2}">View Album</a></div></div></div><img src="{0}" alt=""></div><div class="content"><div class="header">{1}</div></div></div>'.format(photo, album_name,url)
      $("#album").append(d);
      $('.ui.three.stackable.special.cards .image').dimmer({on: 'hover'});
    }
    $.ajax({
      url: 'lists/',
      dataType: 'json',
      success: function(data){
        data['data'].forEach(generateAlbum);
      }
    });
  });
</script>
{% endblock %}

album/templates/album/photo_confirm_delete.html
{% extends 'staff/base_staff.html' %}
{% block main_content %}
  <div class="ui container">
    <div class="ui segment">
      <form class="ui form" method="post">
        {% csrf_token %}
        <h3>Are you sure you want to delete {{ object }}?</h3>
        <div class="ui buttons">
          <a href="{% url 'staff:photos' album=object.album.slug %}" class="ui green button">No</a>
          <input type="submit" value="Confirm" class="ui red button">
        </div>
      </form>
    </div>
  </div>
{% endblock %}

album/templates/album/photo_list.html
{% extends 'staff/base_staff.html' %}
{% load staticfiles %}
{% block album %}
active
{% endblock %}
{% block main_content %}
  <a href="{% url 'staff:albums' %}"class="ui orange button">
    <i class="left angle icon"></i>
    List of all Albums
  </a>
  <div class="ui raised segment">
    <div class="ui grid">
      <div class="row">
        <div class="column">
          <div class="ui placeholder segment">
            <div class="ui icon header">
              <i class="download icon"></i>
              <h2>Drop Photos Here to Upload</h2>
            </div>
            <div class="ui horizontal divider">
              or
            </div>
            <div class="ui blue button" id="upload-photos">
              Click Me
            </div>
          </div>
          <input id="fileupload" name="file" type="file" multiple accept="image/*"
            data-url = "{% url 'staff:upload_photo' album=photos.album_slug %}"
            style="display:none;"
            data-form-data='{"csrfmiddlewaretoken" : "{{ csrf_token }}"}'>
          <h3>{{ photos.album}}</h3>
        </div>
      </div>
      <div class="row">
        <div class="column">
          <h2 class="ui header">Recently Uploaded</h2>
          <div class="ui placeholder segment" id="recently-uploaded">
            <div class="ui segments" style="display:none;" id="uploaded-segments">

            </div>
            <div class="ui icon header" id="image-null-holder">
              <i class="file image outline icon"></i>
              No images uploaded yet
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="column">
          <div class="ui container segment">
            <h2 class="ui header">Pictures in this album</h2>
            <div class="ui divider"></div>
            <table class="ui celled padded table">
              <thead >
                <tr>
                  <td>
                    Picture
                  </td>
                  <td>
                    Action
                  </td>
                </tr>
              </thead>
              <tbody>
                {% for photo in photos.photos %}
                <tr>
                  <td>
                    <img src="{{ photo.file.url }}" alt="" width="250">
                  </td>
                  <td>
                    <a href="{% url 'staff:delete_photo' album=photo.album.slug pk=photo.pk %}" class="ui red button">
                      <i class="remove icon">
                      </i>Delete
                    </a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- MODAL -->
  <div class="ui basic modal">
    <div class="ui icon header">
      <i class="upload icon"></i>
      Uploading images
    </div>
    <div class="content">
      <div class="ui teal progress" id="progress">
        <div class="bar"></div>
        <div class="label" style="color:white;"></div>
      </div>
    </div>
  </div>

{% endblock %}
{% block javascript %}
  <script type="text/javascript" src="{% static 'js/jquery.ui.widget.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.iframe-transport.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.fileupload.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/file_upload.js' %}"></script>
<!-- TODO: Implement a carousel view for all the photos
<script src="http://cdn.jsdelivr.net/jquery.glide/1.0.6/jquery.glide.min.js"></script>
<script type="text/javascript">
  $('.slider').glide();
</script>
-->
{% endblock %}

album/templates/album/photos.html
{% extends 'base_2.html' %}
{% load staticfiles %}
{% block album %}
active
{% endblock album %}
{% block linkstyle %}
  <link rel="stylesheet" href="{% static 'css/glider.css' %}">
{% endblock %}

{% block main_content %}
<div class="ui container">
  <a href="{% url 'album:albums' %}" class="ui orange button icon">
    <i class="left double angle icon"></i>
    Go Back
  </a>
  <div class="ui segment">
    <div class="ui horizontal section divider inverted">
      <h1 class="ui header" id="album-header"></h1>
    </div>
    <div class="glider-contain multiple">
      <button type="button" name="button" class="glider-prev">
        <i class="ui left double angle icon"></i>
      </button>
      <div class="glider">

      </div>
      <button type="button" name="button" class="glider-next">
        <i class="ui right double angle icon"></i>
      </button>
      <div id="dots" class="glider-dots">

      </div>
    </div>
    <p class="ui description" id='album-description'>

    </p>
    <p class="meta" id="album-meta">

    </p>
  </div>
</div>
{% endblock %}
{% block javascript %}
  <script type="text/javascript" src="{% static 'js/glider.js' %}"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      function generatePictures(value, index, array){
        var file = value.file
        var text = `<div class="ui fluid raised card">
          <div class="ui image">
            <img src="` + file + `" alt="" id="carousel-image">
          </div>
        </div>
        `
        console.log(text);
        $('.glider').append(text);
      }
      $.ajax({
          url: 'photos/list',
          dataType: 'json',
          generateJS : function addJS(){
            new Glider(document.querySelector('.glider'), {
              slidesToShow: 1,
              slidesToScroll: 1,
              draggable: true,
              scrollLock: true,
              dots: '#dots',
              arrows : {
                prev : '.glider-prev',
                next: '.glider-next'
              },
              responsive : [{
                breakpoint: 1024,
                settings: {
                  scrollLock: true,
                  slidesToShow: 3,
                  slidesToScroll: 3,
                }
              },
              {
                breakpoint: 768,
                settings: {
                  scrollLock: true,
                  slidesToShow: 2,
                  slidesToScroll: 2,
                }
              }
              ]
            })
          },
          success: function(data){
            data.data.forEach(generatePictures);

            var header = document.getElementById('album-header');
            var description = document.getElementById('album-description')
            var date = document.getElementById('album-meta')

            console.log(data.data[0].date)
            var new_date = new Date(data.data[0].date)
            var month = function(date) {
              const months = [
              "January", "February", "March", "April", "May",
              "June", "July", "August", "September", "October",
              "November", "December"
              ]
              return (months[date.getMonth()])
            }
            console.log("Month: "+ month(new_date));

            console.log("New date: " + month(new_date) + " " + new_date.getDate() + ", " + new_date.getFullYear())

            date.innerText = "Uploaded on " + month(new_date) + " " + new_date.getDate() + ", " + new_date.getFullYear()
            header.innerText = data.data[0].album_title
            description.innerText = data.data[0].album_description
            this.generateJS();
          }
        });
    });
  </script>
{% endblock %}