album/urls.py
from django.urls import path
from . import views

app_name = 'album'

urlpatterns = [
    path('', views.AlbumTemplateView.as_view(), name="albums"),
    path('lists/', views.AlbumList.as_view(), name="albums_list"),
    path('<slug:album>/photos', views.PhotoTemplateView.as_view(), name="photos_list"),
    path('<slug:album>/photos/list/', views.PhotoList.as_view(), name="photos")
]

arachnid/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('staff/', include('staff.urls', namespace="staff")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('albums/', include('album.urls', namespace='album'))
    #path('albums/', include('album.urls', namespace="album"))
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),

    path('admissions',
        views.AdmissionView.as_view(),
        name="admissions"),

    path('news',
        views.NewsView.as_view(),
        name="news"),

    path('news/details/<int:pk>', views.NewsDetailView.as_view(),
        name="news_detail"),

    path('organizations',views.OrganizationListView.as_view(),name="organizations"),
    path('organizations/details/<int:pk>', views.OrganizationDetailView.as_view(), name="organization_details"),


    path('life_science', views.LifeListView.as_view(), name="life_science"),
    path('life_science/details/<int:pk>', views.LifeDetailView.as_view(),name="life_science_detail"),

    path('applied_science', views.AppliedListView.as_view(),name="applied_science"),
    path('applied_science/details/<int:pk>', views.AppliedDetailView.as_view(),name="applied_science_detail"),


    path('about',
        views.AboutView.as_view(),
        name="about"
    ),

    path('faqs',
        views.FAQsView.as_view(),
        name="faqs"
    )
]

staff/urls.py
from django.urls import path, include
from . import views
from album import views as album_views
from django.contrib.auth import views as auth_view

app_name = 'staff'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('announcements/', views.AnnouncementListView.as_view(), name='announcements'),
    path('announcements/create/', views.AnnouncementCreateView.as_view(), name="create_announcement"),
    path('announcements/view/<int:pk>/', views.view_file, name="view_file"),

    path('news/', views.NewsListView.as_view(), name="news"),
    path('news/create/', views.NewsCreateView.as_view(), name="create_news"),
    path('news/update/<int:pk>/', views.NewsUpdateView.as_view(), name="update_news"),
    path('news/delete/<int:pk>/', views.NewsDeleteView.as_view(), name="delete_news"),
    path('news/publish/<int:pk>/', views.publish_news, name="publish"),

    path('organizations/', views.OrganizationListView.as_view(), name="organizations"),
    path('organizations/create/', views.OrganizationCreateView.as_view(), name="create_organization"),
    path('organizations/delete/<int:pk>/', views.OrganizationDeleteView.as_view(), name="delete_organization"),
    path('organizations/update/<int:pk>/', views.OrganizationUpdateView.as_view(), name="update_organization"),
    path('organization/details/<int:pk>/', views.OrganizationDetailView.as_view(), name="organization_detail"),

    path('research/', views.ResearchListView.as_view(), name="research"),
    path('research/create/', views.ResearchCreateView.as_view(), name="create_research"),
    path('research/delete/<int:pk>/', views.ResearchDeleteView.as_view(), name="delete_research"),
    path("research/update/<int:pk>/", views.ResearchUpdateView.as_view(), name="update_research"),
    path("research/details/<int:pk>/", views.ResearchDetailView.as_view(), name="research_detail"),
    path('research/details/<int:pk>/add_proponent/', views.add_proponent_to_research, name="add_proponent_to_research"),

    path('accounts/login/', auth_view.login, name="login"),
    path('accounts/logout/', auth_view.logout, name="logout", kwargs={'next_page': '/'}),

    # For the organization hr
    path('organizations/<organization>/hr/', views.OrganizationHRListView.as_view(), name="organization_hr_list"),
    path('organizations/<organization>/hr/create', views.OrganizationHRCreateView.as_view(), name="organization_hr_create"),
    path('organizations/<organization>/hr/delete/<int:pk>/', views.OrganizationHRDeleteView.as_view(), name="organization_hr_delete"),
    path('organizations/<organization>/hr/update/<int:pk>/', views.OrganizationHRUpdateView.as_view(), name="organization_hr_update"),
    path('organizations/<organization>/hr/details/<int:pk>/', views.OrganizationHRDetailView.as_view(), name="organization_hr_detail"),

    # for the albums section
    path('albums/', album_views.AlbumListView.as_view(), name="albums"),
    path('albums/create', album_views.AlbumCreateView.as_view(), name="create_album"),
    path('albums/delete/<int:pk>/', album_views.AlbumDeleteView.as_view(), name="album_delete"),
    path('albums/<slug:album>/photos/delete/<int:pk>/', album_views.PhotoDeleteView.as_view(), name="delete_photo"),
    path('albums/<slug:album>/photos', album_views.PhotosListView.as_view(), name="photos"),
    path('albums/<slug:album>/photos/upload', album_views.PhotoUploadView.as_view(), name="upload_photo")

]

templates/base.html
<!DOCTYPE html> {% load staticfiles %}
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0" />
    <meta name="description" content="Quezon Science High School" />
    <meta name="author" content="Quezon Science High School" />
    <meta name="keywords" content="quezon,science,honor,excellence,service, quezon science high school, qshs" />
    <title>
        {% block title %} {% endblock %}
    </title>


    <link rel="stylesheet" href="{% static 'dist/semantic.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    {% block linkstyle %}
    {% endblock %}
    <style type="text/css">{% block style %} {% endblock %}</style>

</head>

<body id="home">

    <!-- Hidden Sidebar Menu -->
    <!-- Hidden Sidebar Menu -->
    <div class="ui vertical sidebar inverted menu">
        <div class="item">
            <a href="{% url 'main:index' %}">
                <i class="home icon"></i> Home
            </a>
        </div>
        <div class="item">
            <a href="{% url 'main:admissions' %}">
                <i class="heartbeat icon"></i> Admissions
            </a>
        </div>
        <div class="item">
            <a href="{% url 'main:news' %}">
                <i class="newspaper icon"></i> News
            </a>
        </div>

        <div class="item">
          <a href="{% url 'album:albums' %}">
              <i class="images icon"></i> Gallery
          </a>
          <!--
            <div class="ui accordion">
                <div class="ui inverted title">
                    <i class="ui dropdown icon"></i> Archives
                </div>
                <div class="content">
                    <a class="item" href="#">
                        <i class="file pdf icon"></i> Documents
                    </a>
                    <a class="item" href="{% url 'album:albums' %}">
                        <i class="images icon"></i> Gallery
                    </a>
                </div>
            </div>
          -->
        </div>
        <div class="item">
            <a href="{% url 'main:organizations' %}">
                <i class="users icon"></i> Organizations
            </a>
        </div>
        <div class="item">
            <div class="ui accordion">
                <div class="ui inverted title">
                    <i class="ui dropdown icon"></i> Research
                </div>
                <div class="content">
                    <a class="item" href="{% url 'main:applied_science' %}">
                Applied Science
              </a>
                    <a class="item" href="{% url 'main:life_science' %}">
                Life Science
              </a>
                </div>
            </div>
        </div>
        <div class="item">
            <a href="{% url 'main:about' %}">
                <i class="universal access icon"></i> About
            </a>
        </div>
        <div class="item">
            <a href="{% url 'main:faqs' %}">
                <i class="help circle icon"></i> FAQs
            </a>
        </div>
    </div>

    <!--Folowing Menu -->
    <div class="ui top fixed primary inverted menu">
        <div class="ui container">
            <a class="toc item">
                <i class="sidebar icon"></i> Menu
            </a>
            <a class="header right item" href="{% url 'main:index' %}">
                <img class="logo" src="{% static 'img/logo.png' %}"> QSHS
            </a>
        </div>
    </div>

    {% block main_content %} {% endblock %} {% include 'main/footer.html'%}

    <!-- Citing scripts -->
    <script src="{% static 'js/jquery.min.js'%}"></script>
    <script type="text/javascript" src="{% static 'dist/semantic.js'%}"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</body>

</html>

templates/base_2.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
	<meta charset="utf-8"/>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
	<meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0"/>
  <meta name="description" content="Quezon Science High School"/>
  <meta name="author" content="Quezon Science High School"/>
  <meta name="keywords" content="quezon,science,honor,excellence,service"/>
	<title>
		{% block title %}

		{% endblock %}
	</title>


	<link rel="stylesheet" href="{% static 'dist/semantic.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
	<style>
		{% block style %}
		{% endblock %}
	</style>
	{% block linkstyle %}
	{% endblock %}
</head>
<body>

	<!-- Hidden Sidebar Menu -->
	<div class="ui vertical sidebar inverted menu">
			<div class="item">
					<a href="{% url 'main:index' %}">
							<i class="home icon"></i> Home
					</a>
			</div>
			<div class="item">
					<a href="{% url 'main:admissions' %}">
							<i class="heartbeat icon"></i> Admissions
					</a>
			</div>
			<div class="item">
					<a href="{% url 'main:news' %}">
							<i class="newspaper icon"></i> News
					</a>
			</div>
			<div class="item">
					<div class="ui accordion">
							<div class="ui inverted title">
									<i class="ui dropdown icon"></i> Archives
							</div>
							<div class="content">
									<a class="item" href="#">
											<i class="file pdf icon"></i> Documents
									</a>
									<a class="item" href="{% url 'album:albums' %}">
											<i class="images icon"></i> Album
									</a>
							</div>
					</div>
			</div>
			<div class="item">
					<a href="{% url 'main:organizations' %}">
							<i class="users icon"></i> Organizations
					</a>
			</div>
			<div class="item">
					<div class="ui accordion">
							<div class="ui inverted title">
									<i class="ui dropdown icon"></i> Research
							</div>
							<div class="content">
									<a class="item" href="{% url 'main:applied_science' %}">
							Applied Science
						</a>
									<a class="item" href="{% url 'main:life_science' %}">
							Life Science
						</a>
							</div>
					</div>
			</div>
			<div class="item">
					<a href="{% url 'main:about' %}">
							<i class="universal access icon"></i> About
					</a>
			</div>
			<div class="item">
					<a href="{% url 'main:faqs' %}">
							<i class="help circle icon"></i> FAQs
					</a>
			</div>
	</div>

	<!--Folowing Menu -->
	<div class="ui top fixed primary inverted menu">
			<div class="ui container">
					<a class="toc item">
							<i class="sidebar icon"></i>
							Menu
					</a>
					<a class="header right item" href="{% url 'main:index' %}">
							<img class="logo" src="{% static 'img/logo.png' %}" alt=""> QSHS
					</a>
			</div>
	</div>

		<!-- Page Contents -->

			<div class="ui large top main menu" id="def-navbar">
				<div class="ui container">
					<a class="header item" href="{% url 'main:index' %}"><img class="logo" src="{% static 'img/logo.png' %}">QSHS</a>
					<div class="ui right item">
							<a class="{% block admission %} {%endblock%}item" href="{% url 'main:admissions' %}">Admissions</a>
							<a class="{% block news %} {%endblock%}item" href="{% url 'main:news' %}">News</a>

							<div class="ui dropdown {% block archives %} {% endblock %}item">
								Archives
								<i class="ui dropdown icon"></i>
								<div class="menu">
									<a class="{% block archive_documents %} {% endblock %}item" href="#">Documents</a>
									<div class="ui divider"></div>
									<a class="{% block album %} {% endblock %}item" href="{% url 'album:albums' %}">Album</a>
								</div>
							</div>
						<a class="{% block org %} {% endblock %} item" href="{% url 'main:organizations' %}">Organizations</a>
							<div class="ui dropdown {% block research %} {%endblock%}item">
								Research
								<i class="ui dropdown icon"></i>
								<div class="menu">
									<a class="{% block research_applied %} {%endblock%}item" href="{% url 'main:applied_science' %}">Applied Science</a>
									<div class="ui divider"></div>
									<a class="{% block research_life %} {% endblock %}item" href="{% url 'main:life_science' %}">Life Science</a>
								</div>
							</div>

							<a class="{% block about %} {% endblock %} item" href="{% url 'main:about' %}">About</a>
							<a class="{% block faq %} {% endblock %} item" href="{% url 'main:faqs' %}">FAQs</a>
							{% if user.is_authenticated %}
							<a href="{% url 'admin:index' %}" class="ui item">Admin</a>
							<a href="{% url 'staff:index' %}" class="item">Faculty/Staff</a>
							<a href="{% url 'staff:logout' %}" class="item">Logout</a>
							{% else %}
							<a href="{% url 'staff:login' %}" class="item">Faculty/Staff</a>
							{% endif %}
					</div>
				</div>
			</div>

				{% block main_content %}

				{% endblock %}


			{% include 'main/footer.html' %}
		<script src="{% static 'js/jquery.min.js'%}"></script>
		<script type="text/javascript" src="{% static 'dist/semantic.js'%}"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<script type="text/javascript">
			$('.upper-bound-list').css('color', 'white');
		</script>
		{% block javascript %}
		{% endblock %}

</body>
</html>